#!/usr/bin/env bash

sudo apt update
sudo apt install -y i3 i3lock snapd xautolock xinit zip gzip tar git feh blueman ubuntu-keyring firefox chromium-browser software-properties-common apt-transport-https wget terminator dbus-x11 openssh-server vim rofi python-pip xbindkeys xbindkeys-config curl build-essential cmake cmake-data libcairo2-dev libxcb1-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-randr0-dev libxcb-util0-dev libxcb-xkb-dev pkg-config python-xcbgen xcb-proto libxcb-xrm-dev i3-wm libasound2-dev libmpdclient-dev libiw-dev libcurl4-openssl-dev libpulse-dev libxcb-composite0-dev xcb libxcb-ewmh2cmake cmake-data libcairo2-dev libxcb1-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-randr0-dev libxcb-util0-dev libxcb-xkb-dev pkg-config python-xcbgen xcb-proto libxcb-xrm-dev i3-wm libasound2-dev libmpdclient-dev libiw-dev libcurl4-openssl-dev libpulse-dev libxcb-composite0-dev xcb libxcb-ewmh2

pip install requests

# Install MailSpring
sudo snap install mailspring

## Install Polybar
git clone https://github.com/jaagr/polybar.git
cd polybar && ./build.sh

## Install Vscode
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
sudo apt install code

## Install DBeaver
mkdir -p $HOME/Downloads
wget -q https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb -O $HOME/Downloads/dbeaver.deb
sudo apt install -y $HOME/Downloads/dbeaver.deb
rm -r $HOME/Downloads

## Install font
rm -r $HOME/.fonts
ln -s $(pwd)/fonts $HOME/.fonts
fc-cache -f -v

## Install terminator config
rm -r $HOME/.config/terminator
ln -s $(pwd)/config/terminator $HOME/.config/terminator
wget -q https://git.io/v5Zww -O $HOME"/.config/terminator/plugins/terminator-themes.py"

## Install bashrc bash prompt
ln -s $(pwd)/config/bashrc $HOME/.bashrc
ln -s $(pwd)/scripts/git_prompt.sh $HOME/.git_prompt.sh

# Putting wallpaper and scripts into .config
mkdir -p $HOME/.config/i3-dotfile
ln -s $(pwd)/wallpaper $HOME/.config/i3-dotfile/
ln -s $(pwd)/scripts $HOME/.config/i3-dotfile/

# Symlink vim
ln -s $(pwd)/config/vim/vimrc $HOME/.vimrc

# Symlink xbindkeys
ln -s $(pwd)/config/xbindkeys/xbindkeysrc $HOME/.xbindkeysrc
xbindkeys --poll-rc

# Symlink polybar
ln -s $(pwd)/config/polybar/ $HOME/.config/

# Symlink i3 config
rm -r $HOME/.config/i3
ln -s $(pwd)/config/i3 $HOME/.config/i3
rm $HOME/.git_prompt.sh
i3-msg restart

## Screen rotation
# cvt 1920 1080 60
# xrandr --newmodea
# xrandr --addmode

# Window Manager Up
startx
feh --bg-scale $HOME/.config/i3-dotfile/wallpaper/one.png