#!/usr/bin/env bash

# ----------------------------------------------- PREPARE
sudo apt update
sudo apt install -y zip gzip tar feh blueman ubuntu-keyring \
                    software-properties-common apt-transport-https \
                    wget openssh-server python-pip curl build-essential
pip install requests

# ----------------------------------------------- CREATE

# INSTALL policy kit
sudo apt install -y policykit-desktop-privileges policykit-1-gnome

# INSTALL git [*]
sudo apt install -y git vim

# INSTALL i3wm, i3lock, xautolock, xinit
sudo apt install -y i3 i3lock xautolock xinit

# INSTALL screenshot program
sudo apt install -y xclip scrot

# INSTALL some supporting programs
sudo apt install -y mpd variety arandr wmctrl

# INSTALL xbindkeys
sudo apt install -y xbindkeys xbindkeys-config

# INSTALL rofi
sudo apt install -y rofi

# INSTALL terminator
sudo apt install -y terminator dbus-x11

# INSTALL chromium and firefox
sudo apt install -y firefox chromium-browser

# INSTALL vagrant and virtualbox
sudo apt install -y virtualbox vagrant

# INSTALL nvm
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
export NVM_DIR="${XDG_CONFIG_HOME/:-$HOME/.}nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# ----------------------------------------------- Symlinks

# ADD .fonts to $HOME
rm -r $HOME/.fonts
ln -s $(pwd)/fonts $HOME/.fonts

# ADD bashrc / bash prompt
rm $HOME/.bashrc
ln -s $(pwd)/config/bashrc $HOME/.bashrc
ln -s $(pwd)/scripts/git_prompt.sh $HOME/.git_prompt.sh

# Install terminator config
rm -r $HOME/.config/terminator
ln -s $(pwd)/config/terminator $HOME/.config/terminator
wget -q https://git.io/v5Zww -O $HOME"/.config/terminator/plugins/terminator-themes.py"

# Symlink wallpapers and scripts to .config folder
mkdir -p $HOME/.config/i3-dotfile
ln -s $(pwd)/wallpaper $HOME/.config/i3-dotfile/
ln -s $(pwd)/scripts $HOME/.config/i3-dotfile/

# Symlink xbindkeys
ln -s $(pwd)/config/xbindkeys/xbindkeysrc $HOME/.xbindkeysrc
xbindkeys --poll-rc

# Symlink polybar config
ln -s $(pwd)/config/polybar/ $HOME/.config/

# Symlink i3 config
rm -r $HOME/.config/i3
ln -s $(pwd)/config/i3 $HOME/.config/i3

# Symlink rofi config
rm -r $HOME/.config/rofi
ln -s $(pwd)/config/rofi $HOME/.config/rofi

# Start up window manager / set background
# startx
feh --bg-scale $HOME/.config/i3-dotfile/wallpaper/vim.png

# ----------------------------------------------- CLEAN UP
rm -r $HOME/Downloads
fc-cache -f -v

# Alias
echo "alias pulseaudio-control='~/avocado-dot-file/config/polybar/scripts/pulseaudio-control/pulseaudio-control.bash'" >> ~/.bashrc
